"""Upgrade interviews

Revision ID: 0fdad2f5af26
Revises: ef2b9eb53718
Create Date: 2016-10-17 20:59:07.603322

"""

# revision identifiers, used by Alembic.
revision = '0fdad2f5af26'
down_revision = 'ef2b9eb53718'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['interview_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    op.drop_table('interview_statuses')
    ### end Alembic commands ###
