"""add register_class

Revision ID: 111ce10add34
Revises: 5642c6fd504e
Create Date: 2016-06-02 22:11:12.936040

"""

# revision identifiers, used by Alembic.
revision = '111ce10add34'
down_revision = '5642c6fd504e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registeration', sa.Column('classnum', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registeration', 'classnum')
    ### end Alembic commands ###
