"""add phone

Revision ID: 678fd7ac08f0
Revises: c2662a72f94c
Create Date: 2016-10-14 18:51:08.064976

"""

# revision identifiers, used by Alembic.
revision = '678fd7ac08f0'
down_revision = 'c2662a72f94c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registeration', sa.Column('phone', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registeration', 'phone')
    ### end Alembic commands ###
